import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SessionLayout from './SessionLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Topics',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionLayout>
          { children }
        </SessionLayout>
      </body>
    </html>
  );
}
